const KEY='snag-recorder-review-notes-v1';
const CLOUD=window.SNAG_CLOUD;
const COLLECTION='snag_review_feeds';
const FEED_KEY='snag-recorder-review-feed-v1';
const STATUS_FILE='review-status.json';
let sdkPromise=null,lastPublished='',statusSyncing=false;
const q=s=>document.querySelector(s);
const qa=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const now=()=>new Date().toISOString();
const uid=()=>crypto.randomUUID?crypto.randomUUID():'note-'+Date.now()+'-'+Math.random().toString(36).slice(2);
let notes=load(), filter='open', annotating=false, editingId=null, context=null;

function load(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(notes));renderCount();renderPins();publish(false).catch(()=>{})}
function fmt(v){try{return new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch{return''}}

function mount(){
  const actions=q('.topbar-actions'); if(!actions||q('#reviewNotesButton'))return;
  const annotate=document.createElement('button'); annotate.id='annotateReviewButton'; annotate.className='icon-button notes-top-button'; annotate.type='button'; annotate.innerHTML='<span>⌖</span><span class="notes-label">Annotate</span>'; annotate.setAttribute('aria-label','Annotate this app');
  const button=document.createElement('button'); button.id='reviewNotesButton'; button.className='icon-button notes-top-button'; button.type='button'; button.innerHTML='<span>✎</span><span class="notes-label">Notes</span><span class="notes-count" id="reviewNotesCount"></span>'; button.setAttribute('aria-label','Open review notes');
  actions.prepend(button); actions.prepend(annotate);
  annotate.onclick=()=>toggleAnnotating(); button.onclick=openDialog;
  installDialog(); assignAnchors(); renderCount(); renderPins();
}
function installDialog(){
  const d=document.createElement('dialog'); d.id='reviewNotesDialog'; d.className='notes-dialog';
  d.innerHTML='<div class="notes-shell"><header class="notes-head"><div><p class="eyebrow">APP REVIEW NOTES</p><h2>Notes for review</h2></div><button id="reviewNotesClose" class="notes-close" type="button">×</button></header><div class="notes-body"><div class="notes-toolbar"><button id="newGeneralReviewNote" class="primary-button" type="button">＋ General note</button><button id="selectReviewTarget" class="secondary-button" type="button">⌖ Select an element</button><button id="copyReviewNotes" class="secondary-button" type="button">Copy review pack</button><button id="refreshReviewFeed" class="secondary-button" type="button">Refresh ChatGPT feed</button></div><section id="reviewNoteComposer" class="note-composer hidden"><div class="note-context"><strong id="reviewNoteContextLabel">General note</strong><span id="reviewNoteContextId">page:general</span></div><textarea id="reviewNoteText" rows="6" maxlength="6000" placeholder="What should be reviewed, changed, clarified or kept?"></textarea><div class="note-composer-actions"><button id="cancelReviewNote" class="secondary-button" type="button">Cancel</button><button id="saveReviewNote" class="primary-button" type="button">Save note</button></div></section><div class="notes-filter" id="reviewNotesFilter"><button data-filter="open" class="active" type="button">Open</button><button data-filter="all" type="button">All</button><button data-filter="archived" type="button">Archived</button></div><div id="reviewNotesList" class="notes-list"></div></div></div>';
  document.body.appendChild(d);
  const banner=document.createElement('div'); banner.id='reviewAnnotationBanner'; banner.className='annotation-banner hidden'; banner.innerHTML='<span>Tap a highlighted area to attach a review note.</span><button id="stopReviewAnnotating" type="button">Done</button>'; document.body.appendChild(banner);
  q('#reviewNotesClose').onclick=()=>d.close(); q('#refreshReviewFeed').onclick=()=>publish(true).then(()=>flash('refreshReviewFeed','Feed refreshed')).catch(()=>flash('refreshReviewFeed','Sign in first')); q('#newGeneralReviewNote').onclick=()=>openComposer({anchorId:'page:general',anchorLabel:'General app note'}); q('#selectReviewTarget').onclick=()=>{d.close();toggleAnnotating(true)}; q('#cancelReviewNote').onclick=closeComposer; q('#saveReviewNote').onclick=saveComposer; q('#stopReviewAnnotating').onclick=()=>toggleAnnotating(false); q('#copyReviewNotes').onclick=copyPack;
  q('#reviewNotesFilter').onclick=e=>{const b=e.target.closest('[data-filter]');if(!b)return;filter=b.dataset.filter;qa('#reviewNotesFilter [data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderList()};
  d.addEventListener('cancel',e=>{e.preventDefault();d.close()});
}
function assignAnchors(){
  [['.project-hero','home:project-summary','Project summary'],['.stats-grid','home:status-summary','Status summary'],['.toolbar','home:search-filters','Search and filters'],['.list-header','home:list-heading','Snag list heading'],['#snagList','home:snag-list','Snag list'],['#newSnagButton','home:new-snag','New snag button'],['#projectButton','nav:projects','Projects'],['#settingsButton','nav:settings','Settings'],['#shareButton','project:share','Share project']].forEach(x=>{const el=q(x[0]);if(el){el.dataset.noteAnchor=x[1];el.dataset.noteLabel=x[2]}});
  qa('.stat-card').forEach(el=>{el.dataset.noteAnchor='status:'+el.dataset.statFilter;el.dataset.noteLabel=(el.textContent||'Status').trim().replace(/\s+/g,' ').slice(0,100)});
  qa('.snag-card').forEach(el=>{el.dataset.noteAnchor='snag-card:'+(el.dataset.id||'item');el.dataset.noteLabel=el.querySelector('h3')?.textContent?.trim()||'Snag card'});
}
function openDialog(){assignAnchors();q('#reviewNotesDialog').showModal();renderList()}
function openComposer(ctx,note){context=ctx;editingId=note?.id||null;q('#reviewNoteComposer').classList.remove('hidden');q('#reviewNoteContextLabel').textContent=ctx.anchorLabel;q('#reviewNoteContextId').textContent=ctx.anchorId;q('#reviewNoteText').value=note?.text||'';q('#saveReviewNote').textContent=note?'Save changes':'Save note';setTimeout(()=>q('#reviewNoteText').focus(),20)}
function closeComposer(){editingId=null;context=null;q('#reviewNoteComposer').classList.add('hidden');q('#reviewNoteText').value=''}
function saveComposer(){const text=q('#reviewNoteText').value.trim();if(!text)return q('#reviewNoteText').focus();const old=notes.find(n=>n.id===editingId),t=now(),n={...(old||{}),id:old?.id||uid(),text,anchorId:context?.anchorId||'page:general',anchorLabel:context?.anchorLabel||'General app note',page:location.pathname+location.search,status:old?.status||'open',createdAt:old?.createdAt||t,updatedAt:t};const i=notes.findIndex(x=>x.id===n.id);if(i<0)notes.push(n);else notes[i]=n;save();closeComposer();renderList()}
function renderList(){const host=q('#reviewNotesList');if(!host)return;let list=[...notes].sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt));if(filter==='open')list=list.filter(n=>n.status!=='archived');if(filter==='archived')list=list.filter(n=>n.status==='archived');host.innerHTML=list.length?list.map(n=>'<article class="saved-review-note" data-note-id="'+esc(n.id)+'"><div class="saved-review-note-head"><strong>'+esc(n.anchorLabel)+'</strong><span>'+fmt(n.updatedAt)+'</span></div><p>'+esc(n.text)+'</p><div class="saved-review-note-meta">'+esc(n.anchorId)+'</div><div class="saved-review-note-actions"><button data-action="goto" type="button">Go to</button><button data-action="edit" type="button">Edit</button><button data-action="archive" type="button">'+(n.status==='archived'?'Restore':'Archive')+'</button></div></article>').join(''):'<div class="notes-empty">No notes in this view yet.</div>';qa('#reviewNotesList [data-note-id]').forEach(card=>card.onclick=e=>{const b=e.target.closest('[data-action]');if(!b)return;const n=notes.find(x=>x.id===card.dataset.noteId);if(!n)return;if(b.dataset.action==='edit')openComposer({anchorId:n.anchorId,anchorLabel:n.anchorLabel},n);if(b.dataset.action==='archive'){n.status=n.status==='archived'?'open':'archived';n.updatedAt=now();save();renderList()}if(b.dataset.action==='goto'){q('#reviewNotesDialog').close();const el=qa('[data-note-anchor]').find(x=>x.dataset.noteAnchor===n.anchorId);el?.scrollIntoView({behavior:'smooth',block:'center'});if(el){el.classList.add('note-flash');setTimeout(()=>el.classList.remove('note-flash'),1600)}}})}
function renderCount(){const el=q('#reviewNotesCount');if(!el)return;const n=notes.filter(x=>x.status!=='archived').length;el.textContent=n?String(n):''}
function renderPins(){qa('.note-pin').forEach(x=>x.remove());qa('.has-review-notes').forEach(x=>x.classList.remove('has-review-notes'));const counts=new Map();notes.filter(n=>n.status!=='archived').forEach(n=>counts.set(n.anchorId,(counts.get(n.anchorId)||0)+1));qa('[data-note-anchor]').forEach(el=>{const c=counts.get(el.dataset.noteAnchor)||0;if(!c||['BUTTON','INPUT','SELECT','TEXTAREA'].includes(el.tagName))return;el.classList.add('has-review-notes');const pin=document.createElement('button');pin.type='button';pin.className='note-pin';pin.textContent=c;pin.onclick=e=>{e.preventDefault();e.stopPropagation();openDialog();filter='all';renderList()};el.appendChild(pin)})}
function toggleAnnotating(force){annotating=typeof force==='boolean'?force:!annotating;assignAnchors();document.body.classList.toggle('annotating',annotating);q('#reviewAnnotationBanner')?.classList.toggle('hidden',!annotating)}
function copyPack(){const list=notes.filter(n=>n.status!=='archived'),text=list.map((n,i)=>(i+1)+'. ['+n.anchorLabel+'] '+n.text).join('\n\n')||'No open review notes.';navigator.clipboard.writeText(text);flash('copyReviewNotes','Copied')}
function flash(id,label){const b=q('#'+id);if(!b)return;const old=b.textContent;b.textContent=label;setTimeout(()=>b.textContent=old,1200)}
function feedMeta(){try{return JSON.parse(localStorage.getItem(FEED_KEY)||'null')}catch{return null}}
function saveFeedMeta(v){localStorage.setItem(FEED_KEY,JSON.stringify(v))}
function randomFeedId(){const b=new Uint8Array(32);crypto.getRandomValues(b);return btoa(String.fromCharCode(...b)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function firebase(){if(sdkPromise)return sdkPromise;sdkPromise=(async()=>{if(!CLOUD?.firebase)throw Error('Firebase unavailable');const [A,Auth,F]=await Promise.all([import('https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js'),import('https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js')]);const app=A.getApps()[0]||A.initializeApp(CLOUD.firebase),auth=Auth.getAuth(app);await auth.authStateReady();return{auth,F,db:F.getFirestore(app)}})();return sdkPromise}
function rawUrl(id){const p=CLOUD.firebase.projectId,k=CLOUD.firebase.apiKey;return `https://firestore.googleapis.com/v1/projects/${encodeURIComponent(p)}/databases/%28default%29/documents/${COLLECTION}/${encodeURIComponent(id)}?key=${encodeURIComponent(k)}`}
async function publish(force=false){const f=await firebase();if(!f.auth.currentUser)return false;let meta=feedMeta();if(!meta){meta={id:randomFeedId(),createdAt:now()};saveFeedMeta(meta)}const pending=notes.filter(x=>x.status!=='archived').map(x=>({id:x.id,status:x.status,text:x.text,anchorId:x.anchorId,anchorLabel:x.anchorLabel,page:x.page,createdAt:x.createdAt,updatedAt:x.updatedAt}));const sig=JSON.stringify(pending.map(x=>[x.id,x.updatedAt,x.status,x.text]));if(!force&&sig===lastPublished)return true;const payload={app:'snag',schema:'snag-static-review-v1',repository:'nirav2000/snag',updatedAt:now(),createdAt:meta.createdAt,pendingCount:pending.length,notes:pending};await f.F.setDoc(f.F.doc(f.db,COLLECTION,meta.id),payload,{merge:false});lastPublished=sig;saveFeedMeta({...meta,rawUrl:rawUrl(meta.id),lastPublishedAt:payload.updatedAt});return true}
async function applyStatusLedger(){if(statusSyncing)return;statusSyncing=true;try{const response=await fetch(`${STATUS_FILE}?v=${Date.now()}`,{cache:'no-store'});if(!response.ok)return;const ledger=await response.json();if(ledger?.schema!=='snag-review-status-v1'||!ledger.notes)return;let changed=false;for(const note of notes){const d=ledger.notes[note.id];if(!d?.status||!d.updatedAt)continue;if(Date.parse(d.updatedAt)<=Date.parse(note.reviewStatusUpdatedAt||note.updatedAt||0))continue;note.status=(d.status==='actioned'||d.status==='implemented')?'archived':d.status;note.reviewStatusUpdatedAt=d.updatedAt;note.updatedAt=d.updatedAt;if(d.message)note.reviewStatusMessage=d.message;if(d.commit)note.reviewStatusCommit=d.commit;changed=true}if(changed){save();renderList();await publish(true)}}finally{statusSyncing=false}}
function reviewFeedUrl(){return feedMeta()?.rawUrl||''}
window.SNAG_REVIEW={getOpenNotes:()=>notes.filter(n=>n.status!=='archived'),getFeedUrl:reviewFeedUrl,refresh:()=>publish(true)};
setInterval(()=>{applyStatusLedger().catch(()=>{});publish(false).catch(()=>{})},5000);
window.addEventListener('focus',()=>{applyStatusLedger().catch(()=>{});publish(false).catch(()=>{})});
document.addEventListener('click',e=>{if(!annotating)return;if(e.target.closest('#reviewAnnotationBanner,#reviewNotesDialog,#annotateReviewButton,#reviewNotesButton'))return;const el=e.target.closest('[data-note-anchor]');if(!el)return;e.preventDefault();e.stopPropagation();toggleAnnotating(false);openDialog();openComposer({anchorId:el.dataset.noteAnchor,anchorLabel:el.dataset.noteLabel||'App element'})},true);
const mo=new MutationObserver(()=>{clearTimeout(mo.t);mo.t=setTimeout(()=>{assignAnchors();renderPins()},80)});mo.observe(document.body,{childList:true,subtree:true});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();