import assert from 'node:assert/strict';
import {bulkSnagChange,BULK_ACTIONS} from './snag-bulk.mjs';
const creator='homeowner',first='contractor1',second='contractor2';
const contractor=(uid,name)=>({uid,label:name,role:'contractor',active:true});
const original={id:'S1',createdByUid:creator,assignee:'Electrician',assigneeId:first,participantUids:[creator,first],status:'open',priority:'Normal',archived:false,category:'Home snag',location:'Kitchen'};
const ctx={recipient:contractor(second,'Plumber'),timestamp:'2026-10-08T13:00:00.000Z'};
let x=bulkSnagChange(original,'assign',ctx).patch;
assert.equal(x.assigneeId,second);
assert.deepEqual(new Set(x.participantUids),new Set([creator,second]));
x=bulkSnagChange(original,'grant',ctx).patch;
assert.deepEqual(new Set(x.participantUids),new Set([creator,first,second]));
assert.deepEqual(x.sharedWithUids,[second]);
const shared={...original,participantUids:x.participantUids,sharedWithUids:x.sharedWithUids};
x=bulkSnagChange(shared,'assign',ctx).patch;
assert.equal(x.assigneeId,second);
assert(shared.participantUids.includes(first));
x=bulkSnagChange(shared,'revoke',ctx).patch;
assert(!x.participantUids.includes(second));
assert(!x.sharedWithUids.includes(second));
const selected={...original,assigneeId:second,assignee:'Plumber',participantUids:[creator,first,second],sharedWithUids:[second]};
x=bulkSnagChange(selected,'revoke',ctx).patch;
assert.equal(x.assigneeId,null);
assert.equal(x.assignee,'');
assert.deepEqual(new Set(x.participantUids),new Set([creator,first]));
assert.throws(()=>bulkSnagChange({...original,createdByUid:second},'revoke',ctx),/creator/);
assert.throws(()=>bulkSnagChange(original,'grant',{recipient:{...ctx.recipient,active:false}}),/authorised/);
assert.throws(()=>bulkSnagChange(original,'grant',{recipient:{...ctx.recipient,role:'builder'}}),/authorised/);
assert.throws(()=>bulkSnagChange(original,'assign',{recipient:{...ctx.recipient,uid:''}}),/authorised/);
assert.deepEqual(bulkSnagChange(original,'status',{value:'resolved',timestamp:ctx.timestamp}).patch,{status:'resolved',resolvedAt:ctx.timestamp,updatedAt:ctx.timestamp});
assert.equal(bulkSnagChange(original,'status',{value:'open'}).patch,null);
assert.equal(bulkSnagChange(original,'archive').patch.archived,true);
assert.equal(bulkSnagChange(original,'restore').patch,null);
assert.equal(bulkSnagChange(original,'unassign').patch.participantUids.includes(first),false);
assert.equal(bulkSnagChange(original,'priority',{value:'High'}).patch.priority,'High');
assert.equal(bulkSnagChange(original,'category',{value:'Other'}).patch.category,'Other');
assert.equal(bulkSnagChange(original,'location',{value:'  Landing '}).patch.location,'Landing');
assert.throws(()=>bulkSnagChange(original,'location',{value:''}),/room/);
assert.throws(()=>bulkSnagChange(original,'priority',{value:'Critical'}),/priority/);
assert.throws(()=>bulkSnagChange(original,'rm'),/Unknown/);
assert.equal(Object.keys(BULK_ACTIONS).length,10);
console.log('Snag bulk permissions, assignment, access revocation and update tests passed');
